### ISSUE TITLE
Anyway to limit number of words?

### ISSUE THREAD

**Issue by FASTANDEXTREME** [LeandroBarone/python-ascii_magic#5]
I want my ascii art to be in under 2000 words 
![image](https://user-images.githubusercontent.com/66107594/214058934-a246bf76-c8d5-4c15-a355-7b3acbde5cfc.png)
but it gave me error  
![image](https://user-images.githubusercontent.com/66107594/214059142-033dbd02-1c1c-45f1-85bf-b2d98ec45aa2.png)
how to fix this?

**Comment by LeandroBarone** [comment]
Your code is bugged: you're setting the variable `words_in_art` just once, so the `While` block can't actually end: it's looping until the number of columns is under 0.

You should save the new character count into the variable after re-creating the ascii piece inside the `While` block, or just use len() instead of a variable.

Also, there is another bug: you're adding the triple tildes (line 8 of your code) just once. You should do it again inside of the `While` block, or check if the resulting piece is 1994 characters long, so it is under 2k after adding the triple tildes.
